name: Build and deploy to pantheon

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Add ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Remove known hosts
        run: ssh-keygen -R github.com
      - name: show known host after remove
        run: echo `cat /home/runner/.ssh/known_hosts`
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.KNOWN_HOSTS }} >> /home/runner/.ssh/known_hosts
      - name: show known host after remove
        run: echo `cat /home/runner/.ssh/known_hosts`
      - name: Validate composer
        run: composer validate
      - name: Install dependency
        run: composer install
      - name: Deploy the code
        run: |
          git remote add pantheon ${{ secrets.GIT_REPO_URL }}
          git push pantheon master
      - name: Deployed status
        run: echo "Deployed ...."
