name: Build and deploy to pantheon

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      # - name: some additional command
      #   run: |
      #     ssh-keygen -R github.com
         # eval `ssh-agent -s`
         # ssh-add /home/runner/.ssh/id_rsa
         # ssh-keyscan -H ${{ secrets.KNOWN_HOSTS }} >> ~/.ssh/known_hosts

      - name: Add ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}

      # - name: Test known host
      #   run: |
      #     ls ~/.ssh
      #     ssh -T ${{ secrets.KNOWN_HOSTS }}
      - name: Validate composer
        run: composer validate
      - name: Install dependency
        run: composer install
      - name: Deploy the code
        run: |
          git fetch --unshallow ${{ secrets.GIT_REPO_URL }}
          git remote remove origin
          git init
          git remote add origin ${{ secrets.GIT_REPO_URL }}
          git push -f origin master
      - name: Deployed status
        run: echo "Deployed ...."
